### ISSUE TITLE
No module named util.qdb

### ISSUE THREAD

**Issue by Rajan** [miyyer/qb#1]
turing@ubuntu:~/Documents/QA/qb$ sudo python generate_makefile.py 
turing@ubuntu:~/Documents/QA/qb$ sudo make data/guesses.db 
python guesser/util/format_dan.py --database=data/questions.db --threshold=5
Traceback (most recent call last):
  File "guesser/util/format_dan.py", line 1, in <module>
    from util.qdb import *
ImportError: No module named util.qdb
make: *** [data/deep/params] Error 1

**Comment by Rajan** [comment]
turing@ubuntu:~/Documents/QA/qb$ python
Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 17:02:03) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import sys
>>> sys.path
['', '/home/turing/Documents/QA/qb', '/home/turing/anaconda/lib/python27.zip', '/home/turing/anaconda/lib/python2.7', '/home/turing/anaconda/lib/python2.7/plat-linux2', '/home/turing/anaconda/lib/python2.7/lib-tk', '/home/turing/anaconda/lib/python2.7/lib-old', '/home/turing/anaconda/lib/python2.7/lib-dynload', '/home/turing/anaconda/lib/python2.7/site-packages', '/home/turing/anaconda/lib/python2.7/site-packages/Sphinx-1.3.1-py2.7.egg', '/home/turing/anaconda/lib/python2.7/site-packages/cryptography-0.9.1-py2.7-linux-x86_64.egg', '/home/turing/anaconda/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg']
>>> import util.qdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "util/qdb.py", line 3, in <module>
    from unidecode import unidecode
ImportError: No module named unidecode
>>>

**Comment by Rajan** [comment]
Could make guesses after install unidecode and regex.

**Comment by Rajan** [comment]
Saw a warning... about unicode...

turing@ubuntu:~/Documents/QA/qb$ make data/guesses.db 
python guesser/util/format_dan.py --database=data/questions.db --threshold=5
2374
train 16276
done with  0
done with  5000
done with  10000
done with  15000
train 8845
test 3874
done with  0
test 2601
devtest 0
devtest 0
dev 16298
done with  0
done with  5000
done with  10000
done with  15000
dev 8961
python guesser/util/load_embeddings.py
loading vocab...
guesser/util/load_embeddings.py:16: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  x = wmap[split[0]]

**Comment by hpduong** [comment]
henry@xubuntu:~/Documents/qb$ make data/guesses.db
python guesser/util/format_dan.py --database=data/questions.db --threshold=5
Traceback (most recent call last):
  File "guesser/util/format_dan.py", line 1, in <module>
    from util.qdb import *
ImportError: No module named util.qdb
Makefile:11: recipe for target 'data/deep/params' failed
make: *** [data/deep/params] Error 1

I have unidecode and regex installed.  Do you have any suggestions?  Thanks.

**Comment by EntilZha** [comment]
Hi @hpduong. Thanks for the bug report. I work with Jordan and have spent most of the past year working on QANTA within the `spark` branch.

I mention this because with the NAACL workshop done, that year's worth of work will be getting merged into the master branch in the coming week/weekend. The upgraded version shouldn't have the problem you are describing and be vastly improved in general.

If you would like to work from the current version regardless, I can look into the issue more closely. Thanks!

**Comment by hpduong** [comment]
Oh, great!  Thanks for the update. I can't wait to check it out. 

I just changed the first line in the file "guesser/util/format_dan.py", 

from util.qdb import * => **from qdb import ***

That got it running, but then ran into next issue:

python guesser/util/format_dan.py --database=data/questions.db --threshold=5
2374
train 16276
done with  0
done with  5000
done with  10000
done with  15000
train 8845
test 3874
done with  0
test 2601
devtest 0
devtest 0
dev 16298
done with  0
done with  5000
done with  10000
done with  15000
dev 8961
python guesser/util/load_embeddings.py
loading vocab...
89972 0
Traceback (most recent call last):
  File "guesser/util/load_embeddings.py", line 23, in <module>
    d = len(all_vocab['the'])
KeyError: 'the'
Makefile:11: recipe for target 'data

**Comment by EntilZha** [comment]
Can you `cat` your `data/deep/glove.840B.300d.txt.gz` file? I was trying to do some work with this and noticed that the download url is giving a 404 which may explain the error you are seeing

**Comment by hpduong** [comment]
The download URL in the Makefile didn't work, so I changed it to http://nlp.stanford.edu/data/glove.840B.300d.zip

**Comment by EntilZha** [comment]
Thanks for finding the bug. We haven't run into it since we haven't re-downloaded the file for quite a while now.

I'll be sure to make that change when doing big merge to master
