### ISSUE TITLE
Stuck here

### ISSUE THREAD

**Issue by Rajan** [miyyer/qb#2]
done with epoch  50  epoch error =  320.245559428  min error =  346.556911274
saving model...
validating...
total training instances: 44020
total testing instances: 44555
(for more than 2 hours...) I'm using Lenovo-Y50-70 with 4th gen i7 with around 1000 CUDA units.

**Comment by EntilZha** [comment]
My guess is that it is still training. There is one particular section which takes a *very* long time (~5-20 hours depending on data set, machine, etc). We are working on moving this part of the training to a cluster environment and making it more efficient.

My guess is that it hits here: https://github.com/miyyer/qb/blob/f5a43960d4fa8a930ef027eab6e8925b46831614/guesser/dan.py#L206

Then is spending lots of time training a model here: https://github.com/miyyer/qb/blob/f5a43960d4fa8a930ef027eab6e8925b46831614/guesser/classify/learn_classifiers.py#L62

Hopefully soon I can post some instructions on how to train on a very small data set just to be sure the pipeline works.

**Comment by ezubaric** [comment]
Unfortunately the CUDA doesn't help with this part.  This is a bit of a bottleneck.  I'm doing it right now on a larger dataset and it's taken more than 20 hours so far.
