### ISSUE TITLE
No module named util.build_whoosh

### ISSUE THREAD

**Issue by Rajan** [miyyer/qb#3]
turing@ubuntu:~/Documents/QA/qb$ make data/lm.pkl
mkdir -p data/wikipedia
python extractors/lm.py --min_answers=5
Traceback (most recent call last):
  File "extractors/lm.py", line 19, in <module>
    from util.build_whoosh import text_iterator
ImportError: No module named util.build_whoosh
make: *** [data/lm.pkl] Error 1

**Comment by ezubaric** [comment]
The root qb directory needs to be on your PYTHONPATH

**Comment by Rajan** [comment]
Thanks, it started. Don't know how will it take though.
