### ISSUE TITLE
Pickel stuck at Loki

### ISSUE THREAD

**Issue by Rajan** [miyyer/qb#6]
![screenshot from 2015-09-18 18 39 09](https://cloud.githubusercontent.com/assets/60307/9963611/be86eb18-5e49-11e5-9da1-4f38f00a5330.png)

I wish it to go to Thor.. or something!

**Comment by ezubaric** [comment]
This is pulling data from Wikipedia.  You may have an Internet connection issue.  Perhaps restart the process and see if it goes past this?

**Comment by ezubaric** [comment]
(It'll go much faster since it already has the Wikipedia data you got before.)

**Comment by Rajan** [comment]
Yes. I did download wikifier. Let me restart the process and see.
Do I need to change anything?

**Comment by ezubaric** [comment]
If it's just an Internet connection issue, there should be no issue

**Comment by Rajan** [comment]
The PYTHONPATH variable wasn't available.
I've copied .bashrc to .profile and re-logged in using GUI.
It's been restarted and starting from Loki now. Thank you.
